### ISSUE TITLE
Rename Peer to Delegate

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#137]
### Motivation

Given that `Peer.sol` partially implements the Peer API we think that naming it `Delegate.sol` is an opportunity to define such a partially implemented Peer. Indeed, this contract behaves as a delegate for another peer in the system.

### Proposed Renaming:

`IPeer.sol` -> `IDelegate.sol`

`Peer.sol` -> `Delegate.sol`

`IPeerFactory.sol` -> `IDelegateFactory.sol`

`PeerFactory.sol` -> `DelegateFactory.sol`

### Contract `DelegateFactory`:

- Implements `ILocatorWhitelist`
- Its purpose is to create new `Delegates`

**Comment by ejwessel** [comment]
`Peer.sol` -> `TakerDelegate.sol`
`PeerFrontend.sol`/`Delegate.sol` -> `MakerDelegate.sol`

**Comment by ejwessel** [comment]
Seems there are two factories now. Unless we want to combine them.

`PeerFactory.sol` -> `TakerDelegateFactory.sol`

**Comment by ejwessel** [comment]
Given the following:
> side as a keyword in the protocol shouldn’t relate to which party is setting the price, but instead should specify the known quantity in setting the price. getTakerSideOrder has meant that makerAmount is a known quantity, and the party responsible for pricing completes the order by supplying the unknown quantity, which in this case would be the takerAmount.

it makes sense to rename as follows:
`getMakerSideOrder()` -> `getMakerSideAmount()`
`getTakerSideOrder()` -> `getTakerSideAmount()`

**Comment by poiresel** [comment]
Closing issue has card and implementation have been merged into master
