### ISSUE TITLE
Rename Maker and Taker to Signer and Sender

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#146]
# Summary

This issue is to propose the renaming of the `maker` and `taker` variable names to `signer` and `sender`. A detailed description of the reasons for this proposal is given below.

## Motivation

- **Maker** describes the party who is **setting** prices on the protocol
- **Taker** describes the party who **accepts** prices, and completes a trade
- When it comes to the swap contract, it should not matter who provided liquidity and who decided to take it, what matters is that both parties involved agreed to the swap.
- In every simple decentralised trade, party A signs an order to show that they agree with it, and party B sends it to the smart contract to show that they too agree with it.
- It doesn't matter whether A was the maker or the taker in the order, the signature from A and the transaction from B show that both parties wanted the trade.
- The swap contract always calls the party who signed the order the `maker` and the sender of the transaction the `taker` - despite the fact that the party who signed the order could have been the taker of liquidity.

## Example

- One example where the terms maker and taker become muddled is with on-chain delegate contracts.
Deploying a delegate on-chain and giving it permission to trade for you provides liquidity to the market, and the contract is an on-chain market **maker**.
- However when a trade is submitted to the `Swap` contract from the delegate contract, the delegate is set as the **taker** of the order.
- This is due to the fact that the delegate is the party that sends the order, and the Swap contract requires the `taker` to be the party that sends the order.
- The party that interacts with the delegate contract and **takes** liquidity is the party who signs the order in this situation. This means that they are set as the **maker** of the order so that Swap can process the signature correctly.

## Conclusion

- It feels like terms have become overloaded, no longer meaning what they were initially intended to mean, which makes the code harder to understand and reason about.
- I propose with the names `sender` and `signer` it would abstract away from liquidity and trade initialisation, and instead focus the contracts back onto the approvals of the trade and the security of the smart contracts.

## Consequences

- This issue is to show that `maker` is not synonymous with `signer`, and the same with `taker` and `sender`.
- This is not to suggest that the names `maker` and `taker` are removed from Airswap entirely, but just from the Swap part of the protocol - contract, interacting libraries etc.
- Trades will still have makers and takers of liquidity, which will remain relevant throughout other contracts, libraries and on the website.
- Swap.swap(Order order) sample obj
```{
  "nonce": "100",
  "expiry": "1566941284",
  "signer": {
    "wallet": "0x655...",
    "token": "0x27054b13b1b798b345b591a4d22e6562d47ea75a" (AST),
    "param": "10000",
    "kind": "0x277f8169"
  },
  "sender": {
    "wallet": "0xdea...",
    "token": "0xc778417e063141139fce010982780140aa0cd5ab (WETH)",
    "param": "100000000",
    "kind": "0x277f8169"
  },
  "affiliate": {
    "wallet": "0x0000000000000000000000000000000000000000",
    "token": "0x0000000000000000000000000000000000000000",
    "param": "0",
    "kind": "0x277f8169"
  },
    "signature": {
      "signatory": "0xdea...",
      "version": "0x45",
      "r": "0x589...",
      "s": "0x730...",
      "v": "28"
    }
}

**Comment by dmosites** [comment]
Looking good. Would be consistent with the newest logic of Swap.swap and authorizations.

**Comment by poiresel** [comment]
update of signer sender notation #158 has been merged in so closing issue.
