### ISSUE TITLE
Enforce trading address in Peer

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#148]
# Summary 

Currently the peer allows trades with `order.taker.wallet` of any address. While this doesn't enable any of the Peer owner's tokens to be taken, it does mean that the Peer's rules can be utilized by other addresses, thereby draining the `maxTakerAmount` when the true owner hasn't carried out trades.

## Changes

- Add `tradeWallet` address to the peer, which is set by the owner
- Add a `require` that the `order.taker.wallet` == `tradeWallet` in the `provideOrder` function.

The addition of `tradeWallet` means that the Peer's owner can store their tokens in a different wallet (e.g. a hardware wallet) from the wallet they used to deploy the contract (e.g. a hot wallet), whilst still allowing them to ensure no one uses their peer.

**Comment by ejwessel** [comment]
Example:
Alice is the victim and Bob and Carol are attackers.

1. Alice Creates a `Peer` with a `Rule` and intent on the `Indexer`
1. Bob and Carol want to do a trade, but know that Alice is providing liquidity to the market.
1. Bob creates an order that where Bob is the Maker and Carol is the Taker.
1. Bob submits the order to Alice's `Peer`
1. The `Peer` conducts the trade between Bob and Carol, while also decreasing the `Peer`'s `Rule` amount. No funds are taken from Alice, but Bob and Carol have exchanged.
1. If the amount that was traded between Bob and Carol was a sizable portion of Alice's `Peer`'s `Rule` amount. Alice's `Peer` would no longer providing liquidity to the market and would be shut out from doing any trades.

**Comment by poiresel** [comment]
Peer trade wallet #151 has been merged, thus closing the issue.
