### ISSUE TITLE
Add "Manager" Role to Delegate Contract

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#154]
Currently, only the Owner of a Peer has the right to manage its rules. This is a proposal to enable the Owner of a Peer to give other parties the right to manage its rules.

i.e. if a Manager is to act on behalf of an owner in order to add a rule and set an intent through a Peer. Peer needs the ability to grant such control.

- the contract should have an owner
- the contract should have a list of parties that can set and unset an intent; a whitelist.
- owner is always apart of whitelist

This is a dependency for https://github.com/airswap/airswap-protocols/pull/144

**Comment by dmosites** [comment]
For terminology either *Manager* or *Admin* would work well, akin to *Owner*. In that way, an Owner is always also a Manager / Admin.

**Comment by ejwessel** [comment]
https://github.com/airswap/airswap-protocols/pull/149
