### ISSUE TITLE
Move Wrapper logic to Swap

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#163]
## Few potential flows ideas:
* Have two functions on swap to dictate whether ether or weth transaction
* Similar to the current swap contract V1:
  * Allow someone to send an order with `ether` and receives back some `token`
  * (V2) Allow a `msg.sender` who must then also be the `_order.sender.wallet` send `ether` to the Swap contract
  *  Pass the ether to the signer and not do any conversion
* Slights deviation when a `msg.sender` sends ether and it gets converted to `WETH` when delivered to the `_order.signer.wallet`
    * Allow someone to send an order with `ether` and receive back some `token`
   * (V2) Allow a `msg.sender` who must then also be the `_order.sender.wallet` send `ether` to the Swap contract
   * Swap contract will deposit the `ether` to become `WETH`
   * Swap will move the `WETH` to the `signer` and transfer the tokens to the `msg.sender `(sender wallet)
   * no additional authorizations for sender/signer would be required for this to function
* Signer is sending back `WETH` and now convert it to `ether` before reaching the taker
  * Swap will be performed and the `_signer.token` will be checked to see if it's `WETH` which will kick off the flow
  * then the sender will need to authorize the swap contract to transfer `WETH`
  * It will move the `WETH` to the swap contract and then call `weth.withdraw`
  * Swap will then need a `fallback` function to receive the `ether` returned
  * Swap contract will transfer the `ether` to the `msg.sender`

## Considerations
* Adds more complexity to swap which is the core piece of the swap protocol
* Reduces gas costs potentially (optimizer could help)
* Allow weth-to-weth trxns eth-to-weth trxn and weth-to-eth trxns since all seem like viable sequences dependent on the use case

**Comment by ejwessel** [comment]
Optionality to keep things separate.

**Comment by dmosites** [comment]
After discussing with the team we'll keep the wrapper logic in its own contract outside of Swap.
