### ISSUE TITLE
Make Wrapper work with Delegate

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#167]
## Introduction
- The design of the wrapper contract is purposefully such that `makers` trade WETH, whereas `takers` may prefer to trade ETH.
- This means that the wrapper was designed such that only the `sender` could trade ETH (as the sender is traditionally the order taker).
- However, with the introduction of on-chain makers (aka delegate contracts), the order taker will now sometimes be the order _signer_.
- This needs to be updated for wrapper to work with delegates.
- Furthermore, for the authorizations of addresses to send or sign needs to be considered in this more complex situation.

## Signer and sender updates to Wrapper
- _**The wrapper needs to be updated to allow either party to be the party sending or receiving ETH; currently this must be the sender.**_
- This can be done by pulling certain information out of the order into variables at the start of Wrapper.swap. Then having generic code that can execute using these variables.
- It needs to be decided whether ETH can be traded for WETH - if so, the ETH address should be provided as `0xFFFFFFF` or `0x0`. I think this would make the order clearer.

## Authorizations
- Currently a require statement exists in Wrapper.swap:
```
    require(_order.sender.wallet == msg.sender, "MSG_SENDER_MUST_BE_ORDER_SENDER");
```
- This would prevent the delegate trading through the wrapper, as the `sender.wallet` is not the delegate
- A require could be added `Swap.isAuthorizedSender(sender.wallet, msg.sender)`, or to check `sender.wallet == Delegate(msg.sender).tradeWallet`

**Comment by ejwessel** [comment]
Maybe useful Diagrams
https://www.notion.so/fluidity/Swap-V2-Vulnerabilities-to-check-da452a139cca41f08f9eb000e05d8606

**Comment by ejwessel** [comment]
> This can be done by pulling certain information out of the order into variables at the start of Wrapper.swap. Then having generic code that can execute using these variables.

I'm not really sure what this means. Could you elaborate a bit more?

**Comment by alicevhenshaw** [comment]
Essentially the code for each possible case is quite long, and then you'd need 4 blocks of code for
- wrap for sender
- wrap for signer
- unwrap for sender
- unwrap for signer

I think it will be possible to pull out enough information at the beginning of the function, such that you can code one generic wrap and one generic unwrap that aren't sender/signer specific.

**Comment by ejwessel** [comment]
> It needs to be decided whether ETH can be traded for WETH

What direction? By the Delegate? 

> ETH address should be provided as 0xFFFFFFF or 0x0. I think this would make the order clearer.

I think this change makes the order explicit and is generally beneficial. This could live outside of this issue as an issue of its own I believe.

**Comment by alicevhenshaw** [comment]
> What direction? By the Delegate?

Direction doesn't matter as the wrapper needs to be able to deal with trades symmetrically now (as sender and signer each take the role of maker sometimes). But currently if someone tried to trade ETH for WETH it would break - the party supplying ETH would end up with their WETH being unwrapped to ETH again due to the fact that both WETH and ETH are specified as `address(wethToken)` in orders

**Comment by ejwessel** [comment]
> both WETH and ETH are specified as address(wethToken) in orders

Gotcha, I misunderstood the original bullet point.

**Comment by ejwessel** [comment]
> This can be done by pulling certain information out of the order into variables at the start of Wrapper.swap. Then having generic code that can execute using these variables.

IMO I think this is the hardest part since they are distinct flows each with distinct authorizations for the four cases you noted above.

Do we have an outline of the four flows authorization checks yet? We might be able to find an interesting overlap there.

**Comment by alicevhenshaw** [comment]
I think you're still misunderstanding my point about pulling out variables. I'll draw something up to show you.

**Comment by alicevhenshaw** [comment]
Update from face to face conversations:
- The wrappers for on-chain and off-chain makers would not have any overlap of their use, and so can be completely different contracts. This simplifies the code and makes it easier to reason about. This means that the current wrapper can be left as-is without needing to support delegate trades.
- The separate ETH and WETH trade addresses has been tabled for now.

**Comment by poiresel** [comment]
Closing this in favor of #324 and current work is in a PR: #335
