### ISSUE TITLE
Embed PauserRole Switch on non-audited contracts

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#170]
Purpose: Allow AirSwap to stay in control of deployed smart contracts in testing stages and remove them if issues are found, either through pausing or selfdestruct

Contracts to add these to:

- [x]  [Wrapper](https://github.com/airswap/airswap-protocols/issues/239)
- [x]  [Indexer](https://github.com/airswap/airswap-protocols/issues/181)
- [ ] ... others

Two functions to add:

* just put in PauserRole/ Pausable
* Second function to selfdestruct the contract if in a paused state

**Comment by ejwessel** [comment]
auditing in progress
