### ISSUE TITLE
Consider project structure

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#177]
As the repo has grown, the different folders have become less structured, and the line between `helper` vs `protocol` has become more blurred.

This is just a reminder we should consider the stucture of the repo while we're tidying it up pre-launch.

**Comment by poiresel** [comment]
in terms of structure, could delegate and delegate factory be in the same folder?

To sample options:
```
source/
	delegate
	delegate-factory
	index
	indexer
	swap
	tokens
	types
	wrapper
utils/
	order-utils
	test-utils
```

```
helpers/                 accessory??
	delegate-factory
	tokens
core-protocol/
	delegate
	index
	indexer
	swap
	types
	wrapper
packages
	order-utils
	test-utils
```

**Comment by alicevhenshaw** [comment]
After a meeting this morning, we concluded to go ahead with the first of the above 2 options.
https://github.com/airswap/airswap-protocols/pull/209
