### ISSUE TITLE
Indexer to be Pausable

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#181]
### Description 
In regards to: https://www.notion.so/fluidity/Indexer-Audit-ef2f668a578f4fefa050442933683bac
Related to issue: https://github.com/airswap/airswap-protocols/issues/170

Add Ownable functionality and Pausable functionality to the Indexer.

### Existing Functionality

```
contract Indexer is IIndexer, Ownable {
```

### Proposed Functionality
```
contract Indexer is IIndexer, Ownable, Pausable {
```

We should also add additional functionality that will allow refunding of staked amounts if we've needed to pause due to a security vulnerability.

```
function refundStake(address) onlyOwner {
```
This will only be possible if the contract were paused.

### Reason
As we're in the on going process of development. Until the contracts are audited and we have 100% confidence in the code we should be playing it safe.

Once audited and 100% confident we can relinquish the ownership so that it's entirely decentralized.

### Considerations
During development and before audited the `Indexer` will be centralized and controlled.

**Comment by alicevhenshaw** [comment]
Do you think we should use Pausable as is? (OpenZeppelin Pausable uses PauserRole), or do you think we should just make a smaller Pausable that just uses the owner that's already there?

I don't see us as needing multiple Pausers so could be simpler to use an Owner not a Role. But I do see that it's also easier to use pre-written and pre-audited contract from OZ.

**Comment by alicevhenshaw** [comment]
I propose we don't need the full pausable and pauserrole contracts for this. I would propose the following changes:
```
bool paused = false;

modifier isNotPaused() {
    require(!paused);
    _;
}

modifier isPaused() {
    require(paused);
    _;
}

function triggerPause() onlyOwner isNotPaused {
   paused = true;
}

function returnStake(address staker) onlyOwner isPaused {
    ** do the stuff **
}
```

Then just add `isNotPaused` to the modifiers of every function in the contract.

Thoughts?

**Comment by ejwessel** [comment]
I agree I don't think we need `PauserRoles`
