### ISSUE TITLE
Reduce nonce states to only AVAILABLE or UNAVAILABLE in Swap.sol

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#184]
Propose that having multiple statuses for an order nonce is unnecessarily informative. We can reduce complexity and remove a `require` in `Swap.sol` with the following.

Currently:
* `signerOrderStatus` is either `OPEN` (`0x0`), `TAKEN` (`0x0`), or `CANCELED` (`0x0`)

Proposed:
* Rename `signerOrderStatus` to `signerNonceStatus`
* `signerNonceStatus` is either `AVAILABLE` (`0x0`) or `UNAVAILABLE` (`0x1`)

**Comment by alicevhenshaw** [comment]
Current bytes are wrong in the above description:
`signerOrderStatus is either OPEN (0x00), TAKEN (0x01), or CANCELED (0x02)`

**Comment by dmosites** [comment]
Thanks @alicevhenshaw. Implemented in #185
