### ISSUE TITLE
Remove expiry from authorizations in Swap.sol

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#194]
Currently, the authorization feature, including both signer and sender authorization, takes an expiry value after which the authorization is invalid.

What we see, and will likely see often, is that in practice, these authorizations are set with essentially infinite expiry. This is a proposal to consider removing expiry in favor of a boolean value.

In this discussion we could consider alternate forms of controlling authorizations, for example, specifying a maximum number of swaps that can be performed for a given authorization.

**Comment by poiresel** [comment]
tldr; I like the simple case of making it a boolean.
 
specifying a maximum number of swaps that can be performed for a given authorization. - seems nifty
almost think that if we set the swap to be a boolean, the delegate could have the max number of swaps of something something more complex like x trades in certain interval. wait X time between, basically
