### ISSUE TITLE
Return the score and identifier from Index.getLocators or add comparable call

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#224]
When using the Indexer, the score and identifier are also important information to have when fetching locators.

- `score`: The user needs to know how much they must to stake to rank on the Index.
- `identifier`: The user needs to have the identifier of at least the final entry for pagination.

They should be returned in the same call to represent the same state.

A route may be to return e.g. `(bytes32[], uint256[], address[])` from the `getLocators` call for locators, scores, and identifiers respectively. Alternatively, if only the last entry is useful for pagination, `(bytes32[], uint256[], address)`.

**Comment by poiresel** [comment]
@dmosites can you give a user flow for this, I'm not 100% understanding it?
