### ISSUE TITLE
Indexer.updateStakeAmount function

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#225]
Currently if a user wants to update their amount staked on a market, they have to call `unsetIntent` and then `setIntent`, which requires them signing and sending 2 transactions. Considering the indexer will revolve around only being able to return the first n staked locators, it should be expected that people might want to update their stake to ensure they remain competitive. For this reason I propose a function `updateStakeAmount(signerToken, senderToken, newAmount` that updates the user's staked amount. This function need not be complex - it could merely call `unsetIntent` and `setIntent` internally, but it stops the user from having to sign 2 transactions.

**Comment by dmosites** [comment]
Also for consideration: `setIntent` will `unsetIntent` if one exists before setting the new intent.

**Comment by alicevhenshaw** [comment]
Yes @poiresel, I would say that it could be an increase or a decrease, and tokens are transferred either way.
