### ISSUE TITLE
Add "version" to Order object and get*Order calls to indicate the Swap contract intended for settlement

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#228]
Given that there may be many Swap contracts, whether for different systems, or through incremental versions, two peers will need to agree on which contract they intend to settle trades.

The value of `version` would be a Swap contract address.

**Comment by alicevhenshaw** [comment]
This seems fair

**Comment by dmosites** [comment]
Yes, sorry. Meant to say that the value of `version` would be a Swap contract address.

**Comment by alicevhenshaw** [comment]
Ah I see. I thought you meant the `DOMAIN_VERSION` constant that already exists.

**Comment by poiresel** [comment]
If that's the case, then maybe modify the Types.hashDomain to use the order.version if that's the new verifying contract?

**Comment by dmosites** [comment]
> If that's the case, then maybe modify the Types.hashDomain to use the order.version if that's the new verifying contract? Also recommend calling it versioningAddress / versioningContract or something else appending to indicate this is a contractAddress and not just a a version 1 or 2

The EIP-712 `domainSeparator` is calculated by `hashDomain` at deploy time for each Swap contract, not on a per-order basis. As for naming, agree it should be clear, though it could be clear simply to see that the values and types are addresses.

**Comment by poiresel** [comment]
dmosites 3:03 PM
signatureValidator is flat
signature.validator is nested
it would be a part of Signature struct

**Comment by poiresel** [comment]
Close as #265 has been merged
