### ISSUE TITLE
Move Rules struct

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#230]
- Structs in libraries are merely copied into the contracts they are used within, and do not reference the library itself after compilation
- `Types` is a library that is used as a helper to `Swap` - it stores constants and functions that are used to implement EIP712 for swap, and help with the security of the contract.
- It feels like Rule is out of place in this library - it is not used within Swap, and is not used in the implementation of EIP712 for Swap.
- Rule is only used within the (I)Delegate contract, and so belongs there, not in the Types library.

Moving from https://github.com/airswap/airswap-protocols/issues/226 as the proposed changes evolved away from the original topic there.

**Comment by poiresel** [comment]
Addressed in #246 and closing this issue.
