### ISSUE TITLE
Make events indexed in the IDelegate

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#236]
Make the events indexed for the Delegate

```
  event SetRule(
    address indexed senderToken,
    address indexed signerToken,
    uint256 maxSenderAmount,
    uint256 priceCoef,
    uint256 priceExp
  );
```

```
  event UnsetRule(
    address indexed senderToken,
    address indexed signerToken
  );
```

Consequences:

There will be additional gas costs as indexed params require this.
the formula for emitting an event is:
k = 375, a is 8, and b is 375
k + unindexedBytes * a + indexedTopics * b
so will be adding 750 gas to each event emittance for the 2 indexed params.

**Comment by cloudonshore** [comment]
Worth the gas cost, I'm in support 👍

**Comment by poiresel** [comment]
#246 Closing since PR merged.
