### ISSUE TITLE
Indexes to be destroyed

### ISSUE THREAD

**Issue by hensha256** [airswap/airswap-protocols#240]
We have a way by which to destroy an indexer - `killContract`. However this leaves all of the Index contracts it created deserted with no owner forever. 2 proposed updates (we could have both):

- `Indexer.deleteIndex(signer, sender) onlyOwner` -> `Index.killContract onlyOwner`, which allows us to kill all Indexes before proceeding to kill the indexer.
- Should a final `unsetIntent` on an Index, leaving Index.length at 0, result in the Index being destroyed?

**Comment by poiresel** [comment]
What are the incentives? Is there a way to incentivize this behavior from the community? If we kill Indexes what happens to staked tokens?

**Comment by alicevhenshaw** [comment]
pseudocode of how it could be done. Function on the indexer:
```function destroyIndexes(address[] signerTokens, address[] senderTokens, address recipient) onlyOwner {
     for i = 0 to length-1
          indexes[signerTokens[i]][senderTokens[i]].killContract(recipient)
}```
