### ISSUE TITLE
Delete Rule when maxSenderAmount reaches 0

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#243]
- Should a rule be deleted if maxSenderAmount is 0?
- How does a Delegate with maxSenderAmount = 0 behave on the Indexer? It's found, but provides no value. Should the intent be removed?

**Comment by poiresel** [comment]
What do you see as the consequences? If the rule is deleted, should this impact the staked tokens in that they should also be unstaked?

**Comment by dmosites** [comment]
It's a good idea to consider removing the intent, but it may be disorienting to the delegate owner for the rule to disappear. This would also require a rule to get zeroed out, which requires a trade of an exact amount which may be less common than expected. I'd be for removing intent.

**Comment by alicevhenshaw** [comment]
The ID field of issue #260 would allow the interface to clarify the closed (deleted) rule. The interface would have a way of showing closed rules - whether they were closed before they finished or after. Realistically if a rule hits 0, a user wont then take the time to delete the rule so I thin kit makes sense to delete it for them
