### ISSUE TITLE
Ensure that there are no extraneous dependencies, or dependencies that belong in devDependencies

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#251]
Currently, for example, `indexer` lists `solidity-coverage` as a dependency, when it should be a devDependency.

**Comment by poiresel** [comment]
delegate  needs to be updated as well

Below shows change
  "devDependencies": {
    "@airswap/order-utils": "0.3.3",
    "@airswap/test-utils": "0.1.0",
    "solidity-coverage": "^0.6.3"
  },
  "dependencies": {
    "@airswap/swap": "2.2.0",
    "openzeppelin-solidity": "^v2.2"
  }

**Comment by poiresel** [comment]
Update for delegate-factory 

 "devDependencies": {
    "@airswap/order-utils": "0.3.0",
    "@airswap/test-utils": "0.1.0",
    "solidity-coverage": "^0.6.3"
  },
  "dependencies": {
    "@airswap/delegate": "0.4.0"
  }

**Comment by poiresel** [comment]
Update for index

  "devDependencies": {
    "@airswap/order-utils": "0.3.3",
    "@airswap/test-utils": "0.1.0",
    "@airswap/tokens": "0.1.0",
    "solidity-coverage": "^0.6.3",
    "truffle": "^5.0.24",
    "bignumber.js": "^9.0.0"
  },
  "dependencies": {
    "openzeppelin-solidity": "^v2.2"
  }

**Comment by poiresel** [comment]
#256 Closing as this has been addressed.
