### ISSUE TITLE
Add solidity-docgen in repo to create markdown files for the api docs site.

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#252]

**Comment by dmosites** [comment]
Do we have good examples? Would like to see what can be done to balance automation and polish.

**Comment by poiresel** [comment]
Will get a screenshot for this and more information, since solidity-docgen just creates markdown may be able to transform it a bit from the basic version to make it prettier.

**Comment by poiresel** [comment]
![currentSolidity](https://user-images.githubusercontent.com/2044804/68041165-5574cf00-fca6-11e9-93b3-bcd5cccccfcd.png)
 Base solidity-docgen, working on creating a handlebar template to make it look prettier and contain full natspec

**Comment by poiresel** [comment]
put in a sample doc for swap within https://github.com/airswap/airswap-protocols/tree/docs-add branch.

**Comment by alicevhenshaw** [comment]
I personally think that large amount of explanation in the docs.airswap.io are much more descriptive. e.g. the table of parameters

**Comment by poiresel** [comment]
ok, so will close as this is not value adding.

**Comment by alicevhenshaw** [comment]
I think it would add value if we could generate those tables automatically too. Is that possible?

**Comment by poiresel** [comment]
![Screenshot from 2019-09-18 11-43-03](https://user-images.githubusercontent.com/2044804/68240045-1f9f5580-ffda-11e9-9893-8579af1c7fa5.png)

**Comment by poiresel** [comment]
![updatescreenshot](https://user-images.githubusercontent.com/2044804/68240094-35147f80-ffda-11e9-9af6-f71305a1320e.png)

**Comment by poiresel** [comment]
better?

**Comment by poiresel** [comment]
proposed plan moving forward, once structure is in a good place move to docs repo and pull in the npm package.
