### ISSUE TITLE
Add ID field to rules and emit event on trade

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#260]
When the UI is pulling information on rules, it displays a rule with a bar showing what percentage of that rule has been filled. The Rule struct itself merely decreases the total amount left, however the UI shows each rule with its percentage remaining etc.

Furthermore, if a user closes one rule on token pair X, Y, and later opens a new rule on the same token pair, the UI needs a way to differentiate between trades on the previous rule vs the new rule.

I suggest the following update:
- Each rule has a unique ID, incrementing from 1, so that a new rule on the same token pair as previously has a different ID to differentiate it.
- On success of a call to `Swap.swap`, the Delegate contract emits an event with parameters `ID, delegateTradeAmount`, to allow for easy lookup of the trades a delegate has done on a rule so far.

**Comment by poiresel** [comment]
Does this mean the multiple delegates can have rule 1?

**Comment by poiresel** [comment]
Think its a good idea, just need to scope out the impl of ID, not sure just incrementing by 1 is the best impl, thinking more like a hash between time and values and having the UI use that as a unique identifier is my alternative proprosal.

**Comment by alicevhenshaw** [comment]
After face to face conversation we agreed IDing from 1, 2, 3 etc is the easiest. It allows the frontend to just loop through rules one ID at a time.

**Comment by poiresel** [comment]
mapping(ID => Rule)
mapping(tokens => ID)
then when we want to introduce multiple rules per token pair it;d just be
mapping(tokens => ID[])
and still mapping(ID => Rule)

Think that works for now!

**Comment by dmosites** [comment]
Alternatively, we could emit an event in `provideOrder` that includes the relevant Rule components. This should be sufficiently unique (tokens and price) for the intended product experience

**Comment by poiresel** [comment]
#263 Closing as emitted event is related to this.
