### ISSUE TITLE
Delegate.setRule should take in a Rule struct

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#273]
Reason: 
Consistency across functions as well as consolidates how many parameters are passed to setRule.

Current impl
```
  function setRule(
    address senderToken,
    address signerToken,
    uint256 maxSenderAmount,
    uint256 priceCoef,
    uint256 priceExp
  ) external onlyOwner {
    _setRule(
      senderToken,
      signerToken,
      maxSenderAmount,
      priceCoef,
      priceExp
    );
  }
```
Proposed change
```
  function setRule(
    address senderToken,
    address signerToken,
    Rule calldata rule
  ) external onlyOwner {
    _setRule(
      senderToken,
      signerToken,
      rule.maxSenderAmount,
      rule.priceCoef,
      rule.priceExp   );
  }
```

**Comment by ejwessel** [comment]
We had this when we had `DelegateManager`.
I think given that it's gone now it's a lot clear of an implementation and definitely warranted to reduce complexity on parameter passing.

**Comment by alicevhenshaw** [comment]
The problem with passing it as a struct is you cannot assign calldata into storage or memory. This means if you have
`setRule(Rule rule)`, you cannot then do
`rules[signer][sender] = rule`
instead you have to assign each element of the struct individually
`rules[signer][sender] = Rule(rule.a, rule.b, rule.c, ...)`
so sadly you dont really get any gains from doing it. Its a limitation of the experimental ABI encoder

**Comment by poiresel** [comment]
Ok, closing
