### ISSUE TITLE
setRuleAndIntent can have stuck tokens in Delegate

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#274]
Ensure that unsetRuleAndIntent transfers staking tokens from Indexer to the owner of the delegate

**Comment by alicevhenshaw** [comment]
##Bug explanation

- If `Delegate.setRuleAndIntent` is called once, the Rule is stored in the Delegate, and an Intent to trade is set on the Indexer - including `amountToStake` tokens being `transferFrom` from the delegate owner into the Delegte, and then staked from the Delegate into the Indexer. The Indexer function invoked is `Indexer.setIntent`
- If `Delegate.setRuleAndIntent` is called a _second_ time, with an `amountToStake`, the Delegate assumes that this is the amount of tokens to take from the owner, for the Indexer to then take as stake.
- However, in the second invocation of the function `Indexer.setIntent`, the indexer looks at the difference between the first `amountToStake` and the second `amountToStake`, and either refunds tokens, or takes the difference from the Delegate. This thereby means the Indexer simply transfers the tokens necessary to change the original stake into the updated stake.
- Through this difference in behaviour in the delegate and the indexer, tokens can easily end up stuck in the Delegate.

## Example - increasing stake
**1st stake:** `amountToStake` = 40
Delegate takes 40 from owner, and the Indexer then takes 40 from Delegate in `Indexer.setIntent`
**1st stake:** `amountToStake` = 60
Delegate takes 60 from owner, and the Indexer only takes 20 (the difference) from the Delegate, to end up with 60 tokens total. 40 tokens remain in the Delegate that should be with the owner.

A similar effect occurs when decreasing ones stake.

**Comment by alicevhenshaw** [comment]
This was fixed in https://github.com/airswap/airswap-protocols/pull/277
