### ISSUE TITLE
CreateIndex() event to emit the index created address

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#290]
### Description
Efficiency gain with regard to the number of calls that need to be made.

### Current behavior
1. `Indexer.createIndex()` => `CreateIndex()` event emitted
1. Query `Indexer.indexes[tokenA][tokenB]` obtain `Index` address
1. Query `Index` data 

### Proposed behavior
1. `Indexer.createIndex()` => `CreateIndex()` event emitted with created index address
1. Query `Index` data

### Reason
This reduces a subsequent calls that needs to be made and speed up the UI. If an individual were to use Infura, this would lighten the call load.

**Comment by alicevhenshaw** [comment]
to clarify, the change:
`      emit CreateIndex(signerToken, senderToken);`
to become
`      emit CreateIndex(signerToken, senderToken, indexes[signerToken][senderToken]);`

**Comment by poiresel** [comment]
CreateIndex event emits the created index #305 has been merged.
