### ISSUE TITLE
Include revert reasons for low approvals

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#291]
### Description
> would the usability benefit of including revert reasons for low approvals and balances outweigh the cost? - Don

### Current behavior
There are numerous areas in the code where revert reasons don't exist for approvals.

### Proposed behavior
Add the revert reasons back in.

### Reason
- It's easier to determine why a swap failed
- Better experience for developers
- Better experience for users
- Explicit and clear reason for a failure

**Comment by poiresel** [comment]
Cons:
Adds code redundancy for checking 
Removes code modularity tying erc20 impl to swap contract

Proposal
Add a transferCheck function that could be called by anyone and thus could be called whenever without gas costs as well as people debugging

**Comment by poiresel** [comment]
Seems worth putting this in irrespective of gas concerns as this is a frequent question from current users.
