### ISSUE TITLE
Add preTransferCheck contract to help debug failed trxns

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#292]
Current Behavior:

It's difficult to debug failed transactions without reverts.

```
preTranferCheck() {
# ideally take in a sample order and check if the approvals and balances for a given swap contract line up
}
```

Add a `transferCheck` function that could be called by anyone and thus could be called whenever without gas costs as well as people debugging

**Comment by ejwessel** [comment]
#361

**Comment by poiresel** [comment]
What does AirSwap debugging look like? Swap, Wrapper, Delegate, Indexer, Index

Swap only for now but could use improvements for the other contracts as well.

Pre
    Order-utils
        Input 
        Output
    Pre Swap Checker
        Input
        Output
    Calls in JS Products
    If the PreSwapChecker fails to return a valid

Real-time 
    Revert Msg found on contract
    Failed Trxns to check

Post
    Maker-Reporting kit
    Order-utils

What's easy debugging?
    Allowances as they don't change frequently 
    Well formatted signatures
    Out of gas reverts
    Is it possible based on how much gas was used, to determine the revert type even if you can't see the revert message
    Or any revert msgs that populate on Etherscan

What's harder?
    Balance issues as after X time it's hard to grab balances from a certain time point

**Comment by poiresel** [comment]
Closed with creation of validator repo
