### ISSUE TITLE
QSP-2: Centralization of Power

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#293]
## Description from Quantstamp:

Smart contracts will often have owner variables to designate the person with special privileges to make modifications to the smart
contract. However, this centralization of power needs to be made clear to the users, especially depending on the level of privilege the contract allows to the owner.

## Response from Airswap:

* Ownable and Pauser features have been removed from the Wrapper.  #302
* Pauser and Kill features have been removed from the Indexer.  #307
* In addition, we've added a note within the https://docs.airswap.io/contracts/indexer page disclosing the level of administrative privileges on the Indexer.

**Comment by alicevhenshaw** [comment]
Fixed in https://github.com/airswap/airswap-protocols/pull/302 and https://github.com/airswap/airswap-protocols/pull/307
