### ISSUE TITLE
QSP-7 Gas Usage / for Loop Concerns - Swap.cancel()

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#294]
## Description from Quantstamp:

Contract(s) affected: Swap.sol, Index.sol
Description: Gas usage is a main concern for smart contract developers and users, since high gas costs may prevent users from wanting to use the smart contract. Even worse, some gas usage issues may prevent the contract from providing services entirely. For example, if a for loop requires too much gas to exit, then it may prevent the contract from functioning correctly entirely. It is best to break such loops into individual functions as possible. In particular, the Swap.cancel() function may fail if the array of nonces is too long...
Recommendation: Although the user could re-invoke the Swap.cancel() function by breaking the array up across multiple transactions, we recommend adding a comment to the function's description to indicate such potential issues.

## Response from Airswap:
Will we be fixing this issue?
Yes, we will add a comment to the function's description to indicate potential issues and how to remedy if the array of nonces is too long.

**Comment by alicevhenshaw** [comment]
So my maths on Swap.cancel having analysed cancelling different length arrays of nonces:
- Function overhead: 22201
- Cost to cancel a nonce: 22831
- Therefore cost to cancel 100 nonces: 2,305,301
- Total nonces you could cancel in 1 transaction on mainnet before hitting the block gas limit: 437

**Comment by alicevhenshaw** [comment]
Explanation added to comments in contract https://github.com/airswap/airswap-protocols/pull/306

**Comment by ejwessel** [comment]
Analysis here: https://github.com/airswap/airswap-protocols/pull/315
