### ISSUE TITLE
QSP-5 isValid does not check that the validator contract is correct

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#303]
## Description from Quantstamp

Severity: Low
Contract(s) affected: Swap.sol, Types.sol

Description:
While the Swap contract ensures that an Order is correctly formatted and properly signed in the isValid() function, it does not check that the intended Swap contract, as denoted by the Order.signature.validator field, corresponds to the correct Swap contract. If a sender/signer participates with multiple swap contracts, replay attacks may be possible by re-submitting the order.

Recommendation: The function isValid require(order.signature.validator == address(this)). Related to this, in the EIP712-related hash Types.DOMAIN_HASH(L52-57): it may be beneficial to include chainId in order to prevent attacks that uses a signature that was signed in the testnet become valid in the mainnet.

## Response from AirSwap

The value of `signature.validator` indicates to a party with the order in hand that the order is intended to be used on the Swap contract at the provided address. It is only informative. Separately, there are protections against replay attacks in the hashing algorithm, where the domain separator includes the intended validator.

We are discussing whether to include`chainId` in the EIP712Domain.

**Comment by poiresel** [comment]
close as audit has been reviewed and finalized
