### ISSUE TITLE
Incorporate tradeWallet token balance into delegate quoting logic

### ISSUE THREAD

**Issue by cloudonshore** [airswap/airswap-protocols#313]
Currently in the off-chain protocol, makers use `getMaxQuote` to provide actionable information to takers regarding the maximum liquidity they have available to fill against. 

The `getMaxQuote` defined in the delegate does not take into account the tradeWallet's balance, so if the tradeWallet transfers their assets to another address, getMaxQuote will return an invalid value. Similarly `getSenderSideQuote` & `getSignerSideQuote` will also return an invalid value. 

I propose that in all three of these functions, a var should be defined like `maxAmount = min(rule.maxSenderAmount, tradeWalletTokenBalance)` where `maxAmount` is then used in all the places where `rule.maxSenderAmount` is currently used.

This will make the delegate protocol have the same reliability & guarantees as the off-chain protocol, and will improve UX both in instant and in smart contract integrations against the delegates.

**Comment by poiresel** [comment]
Putting in the code from a previously written validity check for the DelegaterFrontend piece.
``` * @notice Provides check on Delegate to ensure meets reqs for complete trade
  * @dev notice this is just checking delegate is ok
  * @param _delegateAddress address
  * @param _senderAmount uint256
  * @param _senderToken address
  * @return uint256
  */
  function checkDelegateValidity(
  	address _delegateAddress, 
  	uint256 _senderAmount, 
  	address _senderToken
  ) 
  external view returns (uint256 allowedAmount) {
  
      address tradeWalletAddress = IDelegate(_delegateAddress).tradeWallet()
      bool authd = Swap(_swapAddress).senderAuthorized(tradeWalletAddress, _delegateAddress)
      uint256 currentAllowance = IERC20(_senderToken).allowance(tradeWalletAddress, _swapAddress)
  	if (authd) {
  		if (currentAllowance > _senderAmount) {
  			return _takerAmount;
  		} else {
  			return currentAllowance;
  		}
  	}
  	return 0;
  }```
