### ISSUE TITLE
Adding protocols to Indexer

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#366]
Adding a `protocol` param onto the individual Indexes to allow users to determine what protocol to use to engage with a peer found at a locator.

## Current Behavior:

Currently, there is only a single index for each signerToken, senderToken pair. This index can be created by anyone. Users can set their intents through a single Indexer. A user can only stake once per index.

Each type needs to be added and stored somewhere to make it retrievable (we should be able to keep this in the indexer as it's could be as single as an array or a mapping).

The locator parameter is currently overloaded in that it can mean either a bytes32 contract address or serve as a URL to a server or something else. And even so, said locator can go through different paths before reaching settlement, ie different APIs exposed, whether they want to sign or send the order....
The front end handles the parsing right now, but there is a real future that this is cumbersome and would not scale.

## New Behavior:

Adding a new field to be (networkType/type/port/channel/commPath) to be another key to index intents by. 
`signerToken`-> `senderToken` -> `field` -> `Index`
`mapping (address => mapping (address => bytes?) => Index)) public indexes;`

For these fields as well, they could be associated with a particular locatorWhitelist as well that can be set. 

getLocators should return 
```
    bytes32[] memory locators,
    uint256[] memory scores,
    address nextCursor
```

Token blacklists will still work across all indices as they current have done.

*No modifications on the index should need to take place. It will continue to just be a reverse ordered circular linked list.*

### What this allows:

    Having a field that embodies how to communicator coupled with the locator where, allows for cleaner messaging
    Within the smart contract can filter by this field when fetching intents
    Allows users to communicate on these different channels

### Cons

    amortized costs of index creation could increase

**Comment by poiresel** [comment]
Protocol in indexer #371 closing since work is completed.

**Comment by wjmelements** [comment]
Why bytes2 instead of bytes16 or bytes32?

There are 2 bytes in TCP port, and https is 443. There will likely be at least 2^16 TCP protocols, but if you include contract interfaces you should use bytes4. So probably something more future-proof would be much larger than 2 bytes.
