### ISSUE TITLE
Add extra fields to order struct

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#367]
Current Behavior:
 ```
  struct Party {
    bytes4 kind;                  // Interface ID of the token
    address wallet;               // Wallet address of the party
    address token;                // Contract address of the token
    uint256 param;                // Value (ERC-20) or ID (ERC-721)
  }
```

New Behavior:
```
  struct Party {
    bytes4 kind;                  // Interface ID of the token
    address wallet;               // Wallet address of the party
    address token;                // Contract address of the token
    uint256 amount;               // Value (ERC-20)
    uint256 id;                   // Add another uint256 that would serve as ID (ERC-721)
  }
```

In addition to how the token registry design work: 
https://github.com/airswap/airswap-protocols/pull/364

**Comment by ejwessel** [comment]
## Migration Plan 

### Contracts

- [ ]  Types.sol
- [ ]  Delegate, IDelegate
- [ ]  Swap, ISwap
- [ ]  Migration.md
- [ ]  Wrapper
- [ ]  Order Utils
- [ ]  Pre-Swap Checker

### Maker

- [ ]  get*Quote
- [ ]  get*Order

### Maker Kit

- [ ]  Handlers

### AirSwap.js

**Comment by ejwessel** [comment]
Tests need to be updated.

**Comment by ejwessel** [comment]
implemented in https://github.com/airswap/airswap-protocols/pull/370
