### ISSUE TITLE
Parallelize Coverage

### ISSUE THREAD

**Issue by ejwessel** [airswap/airswap-protocols#384]
## Description 
Parallelize circle ci tests to also run coverage

## Current Implementation
- currently coverage is run locally
- coverage is run from a package directory
- coverage needs to handle inherited `view` methods by removing `view`
- copy paste output to PR

## Proposed Implementation
- run coverage on circle ci
- circle ci would copy the relevant files and remove the relevant view methods
- run coverage
- produce output

## Reason
Coverage takes too long to run locally.

<img width="421" alt="Screen Shot 2019-12-18 at 11 26 16 AM" src="https://user-images.githubusercontent.com/3590816/71104069-387a5980-2189-11ea-8ab1-9ceedf71ac57.png">

**Comment by poiresel** [comment]
Has been completed https://github.com/airswap/airswap-protocols/pull/348
