### ISSUE TITLE
Add TheGraph subgraphs to improve data availabiltiy

### ISSUE THREAD

**Issue by poiresel** [airswap/airswap-protocols#500]
* Creating subgraphs for all deployed contracts so far in airswap-protocols for different chains
* Further narrow down popular query mechanics and build bespke graphs on these patterns

**Comment by ejwessel** [comment]
https://github.com/airswap/airswap-protocols/pull/506

**Comment by ejwessel** [comment]
Custom Queries: https://github.com/airswap/airswap-protocols/pull/511

**Comment by ejwessel** [comment]
@dmosites did we want to deploy for other networks?

**Comment by ejwessel** [comment]
example and custom queries are available in AirSwap.postman.json within `airswap-protocols/tools/subgraph`
