### ISSUE TITLE
WTF are you doing here? Who Stole my Coins???

### ISSUE THREAD

**Issue by Degget1986** [airswap/airswap-protocols#627]
WTF is that AirSwap Deployer3?
0x7F18BB4Dd92CF2404C54CBa1A9BE4A1153bdb078

And why you Stole my Money?

WTF is the Metamask: Swap Router: 0x881D40237659C251811CEC9c364ef91dC08D300C

Give Back my Money !!!

**Comment by dmosites** [comment]
Hello, please reach MetaMask Support here: https://metamask.zendesk.com/hc/en-us/requests/new or reach them by emailing support@metamask.io.
