### ISSUE TITLE
Deploy latest protocols to Rinkeby and Goerli

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#668]
light, registry, token

**Comment by parseb** [comment]
Assign this to me if not urgent. 
Have to familiarize myself with hardhat. 
![image](https://user-images.githubusercontent.com/5999852/146071687-e4ba7447-989c-4dba-bcee-c56fe7d17380.png)
Link not working. Let me know if there's a guide. (Not an issue if none.)
