### ISSUE TITLE
PVE002: Improved Logic of Pool:withdrawAndStakeFor()

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#777]
![photo_2022-01-28 13 23 11](https://user-images.githubusercontent.com/1601469/151546471-a78697c7-6fb5-4a7e-b9cb-c755682c763d.jpeg)

**Comment by francisldn** [comment]
While the staking contract is approved for the max amount in ``setStakingToken``, I think it's good to reset the allowance to the minimum required amount in this instance. Any other views?

**Comment by AboldUSER** [comment]
Just to leave a comment on how this was updated, the redundant approve was removed as the approval on initialization sets to the max amount.
