### ISSUE TITLE
PVE003: Just-in-Time Balance for Maximum Swap Discount

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#780]
![photo_2022-01-28 13 23 16](https://user-images.githubusercontent.com/1601469/151546625-5d0da8dd-846d-4b9d-a93d-dcc0705875e2.jpeg)

**Comment by AboldUSER** [comment]
I believe this should actually be checking the balanceOf the staking token within the staking contract, not just the staking token within the msg.sender's account.
