### ISSUE TITLE
PVE004-2: Accommodation of Non-ERC20-Compliant Tokens

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#782]
![photo_2022-01-28 13 23 18](https://user-images.githubusercontent.com/1601469/151546687-8c7d29ed-023a-4309-8227-fc9dd4b35367.jpeg)

**Comment by AboldUSER** [comment]
In pool contract replaced approve with safeApprove as it initializes an allowance from zero and resets an allowance to zero
