### ISSUE TITLE
PVE005: Trust Issue of Admin Keys (Questionable if EOA)

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#783]
![photo_2022-01-28 13 23 19](https://user-images.githubusercontent.com/1601469/151546719-583c9dbd-4af7-4f12-a6f8-cd43cf61402b.jpeg)

**Comment by AboldUSER** [comment]
All AirSwap contracts are managed by a multi-sig contract to avoid risk of any single compromised EOA or malicious action from an EOA

**Comment by francisldn** [comment]
Closing this issue as we agreed that it is a non-issue.
