### ISSUE TITLE
Q1: Staking::unsetDelegate()

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#784]
![photo_2022-01-28 13 23 21](https://user-images.githubusercontent.com/1601469/151546733-e1bca094-edfd-4d3a-be51-89b5adaae926.jpeg)

**Comment by AboldUSER** [comment]
I don't think we need to check if the msg.sender is staking, as this is called by the account that proposes or removes a delegate and not the delegate itself.

**Comment by francisldn** [comment]
Closing this issue as we agreed that it is a non-issue.
