### ISSUE TITLE
Dependency looks for JS files but they are now TS files

### ISSUE THREAD

**Issue by Luiscmogrovejo** [airswap/airswap-protocols#852]
Code in swap function gives this error
![unknown](https://user-images.githubusercontent.com/101224235/172192544-41654289-9c2e-4c9c-b818-29b9ca04f249.png)
```
import { Server, Swap, Registry } from '@airswap/libraries';
```
Also, when I call the contract via ethers directly I get the same error message using
```
    const serverPromises = await Promise.allSettled(
      quoteTokenURLs
        .filter((value) => baseTokenURLs.includes(value))
        .map((url) => {
          return Server.at(url, {
            swapContract:
              options?.swapContract || Swap.getAddress(this.chainId),
            initializeTimeout: options?.initializeTimeout,
          })
        })
    )
```

I get the Url for the quotes right but can't get to make this function work on my side or with the library.
I think Server is looking for a js file instead of ts

![image](https://user-images.githubusercontent.com/101224235/172192623-3d5b5faf-90da-42db-b277-47afc04e5420.png)

**Comment by dmosites** [comment]
Sorry we missed this @Luiscmogrovejo. What version of `@airswap/libraries` were you using?

**Comment by dmosites** [comment]
This should be fixed in the latest version of the `@airswap/libraries` package.
