### ISSUE TITLE
Swap Audit: 3.2 OpenZeppelin’s Ownable Library is Risky when Transferring Ownership

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#891]

**Comment by dmosites** [comment]
We recommend using a two-step pattern in which a new owner is proposed by the current one and the pending owner is required to claim the new ownership.

**Comment by Perelyn-sama** [comment]
https://github.com/byterocket/solrocket/blob/f0dd2e593c34ec2878424f2110f37cfec715f60e/src/TSOwnable.sol

**Comment by dmosites** [comment]
Addressed here: https://github.com/airswap/airswap-protocols/pull/899#issuecomment-1259902130
