### ISSUE TITLE
Swap Audit: 3.3 Use Custom Errors to Save Gas

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#892]

**Comment by dmosites** [comment]
> We recommend upgrading the compiler to the latest version and using [custom errors](https://docs.soliditylang.org/en/v0.8.15/contracts.html#errors-and-the-revert-statement) to save gas.

**Comment by Perelyn-sama** [comment]
So we would have to replace all the require's to with custom errors and reverts
