### ISSUE TITLE
Swap Audit: 3.4 Avoid abi.encodePacked for Hashing Static Strings to Save Deployment Cost

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-protocols#893]

**Comment by dmosites** [comment]
> Avoid unnecessary operations to save deployment cost:
> ```
>     bytes32 public constant DOMAIN_TYPEHASH_WITHOUT =
>     keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)");
> ```

**Comment by Perelyn-sama** [comment]
Fixed at https://github.com/airswap/airswap-protocols/pull/900
